apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yggdrasil
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/distributed-technologies/helm-overdrive-poc.git
    targetRevision: main
    path: .
    plugin:
      name: helm-overdrive-app-discover
