apiVersion: argocd-discover/v1alpha1
name: hello-world
namespace: monitoring
createNamespace: false
project: monitoring
source:
  helm_repo: https://helm.github.io/examples
  chart_name: hello-world
  chart_version: 0.1.0
